name: Debug Build CI

on:
 workflow_dispatch:
 push:
   branches:
     - main
     - master
     - dev

jobs:
 build-debug:
   name: Build Debug APK
   runs-on: azu
   steps:
     - uses: actions/checkout@v4

     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Build Debug APK (without git SHA)
       run: ./gradlew assembleFdroidRelease
       env:
         EXCLUDE_GIT_INFO: true
       continue-on-error: false

     - name: Rename Debug APK
       run: |
         mkdir -p app/build/outputs/apk/release-artifacts
         cp app/build/outputs/apk/Fdroid/release/*.apk app/build/outputs/apk/release-artifacts/reterminal-release.apk

     - name: Upload Debug APK
       uses: actions/upload-artifact@v4
       with:
         name: ReTerminal-Debug
         path: app/build/outputs/apk/release-artifacts/reterminal-release.apk
