name: Build CI

on:
  workflow_dispatch:
  label:
    types: [created, edited]
  push:
    branches:
      - main
      - 'releases/**'
      - 'refs/**'
      - '**'
      - 'copilot/**'
      - 'refs/remotes/origin/copilot/**'
      - 'refs/origin/copilot/**'
      - 'refs/copilot/**'
      - 'refs/heads/copilot/**'
  pull_request:
    branches:
      - main
      - 'releases/**'
      - 'refs/**'
      - '**'
      - 'copilot/**'
      - 'refs/remotes/origin/copilot/**'
      - 'refs/origin/copilot/**'
      - 'refs/copilot/**'
      - 'refs/heads/copilot/**'
  create:
    branches:
      - main
      - 'releases/**'
      - 'refs/**'
      - '**'
      - 'copilot/**'
      - 'refs/remotes/origin/copilot/**'
      - 'refs/origin/copilot/**'
      - 'refs/copilot/**'
      - 'refs/heads/copilot/**'
  issues:
    types: 
      - opened
      - reopened
      - closed
      - labeled

jobs:
 build-debug:
   name: Build Debug APK
   runs-on: azu
   permissions:
      issues: write
      pull-requests: write
      contents: write
      actions: write          # Permite ejecutar y modificar workflows
      checks: write           # Permite crear y modificar checks (revisiones)
      repository-projects: write
      statuses: write
      discussions: write
      deployments: write
      attestations: write
   
   steps:
     - uses: actions/checkout@v4

     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Build Debug APK (without git SHA)
       run: ./gradlew assembleFdroidRelease
       env:
         EXCLUDE_GIT_INFO: true
       continue-on-error: false

     - name: Rename Debug APK
       run: |
         mkdir -p app/build/outputs/apk/release-artifacts
         cp app/build/outputs/apk/Fdroid/release/*.apk app/build/outputs/apk/release-artifacts/reterminal-release.apk

     - name: Upload Debug APK
       uses: actions/upload-artifact@v4
       with:
         name: ReTerminal-Release
         path: app/build/outputs/apk/release-artifacts/reterminal-release.apk
